### ISSUE TITLE
All User Stories Checklist

### ISSUE THREAD

**Issue by andrewniekamp** [andrewniekamp/grace-shopper#2]
# As a visitor, I want to...

## PRODUCTS

- [x] view the full list of products (the product catalog), so that I can see everything that's available
- [ ] refine product listings by category, so that I can narrow down my choices to see only the types of items I'm interested in
- [ ] search product listings, so that I can find specific products I want by name
- [x] view the details for an inidivdual product (including product descriptions, photos and reviews), so that I can determine whether that particular item fits my needs

## CART

- [x] add items to my cart from the product listing or product detail pages, so that I can purchase them later
- [x] remove items from my cart, in case I decide I don't want an item anymore
- [ ] edit/remove quantities of items in the cart, in case I decide I want more or less of a particular item
- [ ] refresh the page and have the cart persist, so that I don't lose my work (you may use sessionStorage, localStorage, cookies or JWT for this)
- [ ] be able to log in to my account and continue editing that same cart, so that I don't lose any progress I made before I logged in

## CHECKOUT

- [ ] purchase items in the cart, so that I can get the items I want
- [ ] specify a shipping address and email address when I checkout, so that the items can arrive at the right place
- [ ] receive a confirmation email after I checkout, so that I know my order is being looked at
- [ ] receive a notification email when the order ships, and then when the order is delivered, so that I can stay up to date on when my order will arrive

## ACCOUNT MANAGEMENT

- [ ] be able to create an account, so that I can perform activities like leaving reviews
- [ ] be able to login with either Google or Facebook, so that I don't need to remember a new password to have an account
