### ISSUE TITLE
Auth. User Stories Checklist

### ISSUE THREAD

**Issue by andrewniekamp** [andrewniekamp/grace-shopper#3]
# As a logged-in user, I want to...

## ACCOUNT MANAGEMENT

- [ ] be able to log out, so that someone else can't just come along and use my account
- [ ] view my list of previous orders, so that I can find and individual order I made in the past and review it
- [ ] view the details of a past order, including...
Current order status
Items with quantity and subtotal
Link to the original product detail page
Date/time order was created
- [ ] so that I can remember exactly what I ordered and when

## REVIEWS

- [x] be able to leave reviews for products (including text and a 5-star rating), so that I can share my experiences with other visitors
