### ISSUE TITLE
Admin. User Stories Checklist

### ISSUE THREAD

**Issue by andrewniekamp** [andrewniekamp/grace-shopper#5]
# As an admin user, I want to...

## PRODUCT MANAGEMENT

- [ ]  create and edit products with name, description, price and one or more photos, so that visitors can see the latest info on what we have to offer
- [x]  create categories for items, so that users can continue to have useful filters as our inventory grows in variety
- [ ]  add/remove categories from items, so that users will see them when they refine their searches
Acceptance Criteria: items must have multiple categories
- [ ]  manage the availability of a product, so that users will know whether or not they can purchase that product
Acceptance Criteria: If a product is no longer available, users will not see it while browsing, but they can view the product detail page if they've ordered it previously or have a direct link. On that product detail page, it should say "Currently Unavailable"

## ORDER MANAGEMENT

- [ ]  view a list of all orders, so that I can find specific orders to review
- [ ]  filter orders by status (Created, Processing, Cancelled, Completed), so that I can more easily find the orders I'm interested in
- [ ]  view details of a specific order, so that I can review it and update its status
- [ ]  change the status of the order (Created -> Processing, Processing -> Cancelled || Completed), so that others will know what stage of the process the order is in

## USER MANAGEMENT

- [ ]  promote other user accounts to have admin status, so that new administrators can have the same privileges I have
- [ ]  delete a user, so users who should not be able to log in anymore cannot
- [ ]  trigger password reset for a user (that is, the next time they successfully log in with their old password, they are prompted for a new one), so that I can be proactive in getting users to change their passwords after a period of time
